spring:
  h2:
    console:
      enabled: true
  datasource:
    username: beer_order_service
    password: 123
    url: jdbc:h2:mem:beerorderdb;DATABASE_TO_LOWER=TRUE;MODE=MYSQL
    drive-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true