spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123
logging:
  level:
    guru: debug
server:
  port: 8081
kkr:
  beer-service:
    host: http://localhost:8080